language: node_js
os: linux
node_js:
  - "stable"
cache:
  directories:
    - app/node_modules
script:
  - npm install
  - npm test
  - npm run build
before_deploy:
  - zip build.zip build/*
deploy:
  provider: releases
  token: $github_token
  file: "build.zip"
  cleanup: false
  draft: true
