os: linux
language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm install
  - npm test
  - npm run build
before_deploy:
  - zip build.zip build/*
  - pwd
  - ls -l
deploy:
  provider: releases
  token: $github_token
  file: ${TRAVIS_BUILD_DIR}/build.zip
  cleanup: false
  draft: true
