os: linux
language: node_js
node_js:
  - "stable"
script:
  - npm install
  - npm test
  - npm run build
before_deploy:
  - zip -r build_${TRAVIS_COMMIT}.zip build/*
deploy:
  provider: releases
  token: $github_token
  file: build_${TRAVIS_COMMIT}.zip
  skip_cleanup: true
  draft: true
